Updated winform sample to show raising of intents from .NET
built-on-openfin/interop-api pull request #5
Opened 2022-08-10 11:10 UTC by andy-westacott

Also updated the required version of the adapter

2022-08-22 11:28 UTC, obany requested changes
Couple of small tweaks

2022-08-22 11:28 UTC, obany commented on csharp/winform/OpenFin.Interop.Win.Sample/MainWindow.cs
> +                fireIntent.Enabled = true;
Could we make the fireIntent only enabled if context type is contact

2022-08-22 11:28 UTC, obany commented on csharp/winform/OpenFin.Interop.Win.Sample/OpenFinIntegration.cs
> +        public async void FireIntent()
Can we pass the selected contact from the Contacts drop down ?

2022-08-22 14:23 UTC, johnman approved these changes

2022-08-22 18:54 UTC, andy-westacott commented on csharp/winform/OpenFin.Interop.Win.Sample/MainWindow.cs
> +                fireIntent.Enabled = true;
done

2022-08-22 18:54 UTC, andy-westacott commented on csharp/winform/OpenFin.Interop.Win.Sample/OpenFinIntegration.cs
> +        public async void FireIntent()
done

2022-08-22 18:55 UTC, andy-westacott commented on csharp/winform/OpenFin.Interop.Win.Sample/OpenFinIntegration.cs
> +        public async void FireIntent()
yep.  sounds good.  Want to do this now or as a separate PR?

2022-08-22 19:09 UTC, johnman approved these changes

2022-08-23 05:18 UTC, obany approved these changes

2022-08-23 08:07 UTC, merged